 prometheus:
  name: prometheus
  appName: prometheus
  namespace: kube-system
  replicas: 2
  containers:
    prometheus:
      image:
        repository: prom/prometheus
        tag: v2.37.6
      args: [
        "--config.file=/etc/prometheus/prometheus.yml",
        "--storage.tsdb.path=/prometheus" ]
      port: 9090
      runAsUser: 0  # Running as Non-user
  scrapeConfigs:
    scrapeInterval: 15s
    evaluationInterval: 15s
    # TODO: Pending to implement in config-map.yaml
    # scraper:
    #   kubernetes_sd_configs:
    #     - role: pod
    #   relabel_configs:
    #     - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
    #       action: keep
    #       regex: true
    #     - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
    #       action: replace
    #       target_label: __metrics_path__
    #       regex: (.+)
    #     - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
    #       action: replace
    #       target_label: __address__
    #       regex: (.+)(?::\d+);(\d+)
    #     - action: labelmap
    #       regex: __meta_kubernetes_pod_label_(.+)
    #     - source_labels: [__meta_kubernetes_namespace]
    #       action: replace
    #       target_label: kubernetes_namespace
    #     - source_labels: [__meta_kubernetes_pod_name]
    #       action: replace
    #       target_label: kubernetes_pod_name