apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Values.fluentd.name }}-config
    namespace: kube-system
data:
    fluentd.conf: |
        <match kubernetes*>
            @type null
        </match>
        <match docker*>
            @type file
            path /var/log/fluent/docker.log
            time_slice_format %Y%m%d
            time_slice_wait 10m
            time_format %Y%m%dT%H%M%S%z
            compress gzip
            utc
        </match>
        <source>
            @type tail
            @id in_tail_container_logs
            path /var/log/containers/*.log
            pos_file /var/log/fluentd-containers.log.pos
            tag kubernetes
            read_from_head true
            <parse>
                @type json
                time_format %Y-%m-%dT%H:%M:%S.%NZ
            </parse>
        </source>