apiVersion: apps/v1
kind: DaemonSet
metadata:
  {{- with .Values.fluentd }}
  name: {{ .name }}
  namespace: {{ .namespace }}
  labels:
    k8s-app: {{ .k8sAppName }}
spec:
  selector:
    matchLabels:
      k8s-app: {{ .k8sAppName }}
  template:
    metadata:
      labels:
        k8s-app: {{ .k8sAppName }}
    spec:
      serviceAccount: {{ .name }}
      serviceAccountName: {{ .name }}
      tolerations:
      {{- with .spec.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .name }}
  {{- end }}
        image: {{ .Values.fluentd.containers.env.fluent.elastic.image }}
        {{- with .Values.global.containers.env.elastic }}
        env:
          - name: K8S_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name:  FLUENT_ELASTICSEARCH_HOST
            value: {{ .host | quote }}
          - name:  FLUENT_ELASTICSEARCH_PORT
            value: {{ .port | quote }}
          - name: FLUENT_ELASTICSEARCH_SCHEME
            value: {{ .scheme | quote }}
          - name: FLUENT_ELASTICSEARCH_SSL_VERIFY
            value: {{ $.Values.fluentd.containers.env.fluent.elastic.sslVerify | quote }}
          - name: FLUENT_ELASTICSEARCH_SSL_VERSION
            value: {{ $.Values.fluentd.containers.env.fluent.elastic.sslVersion | quote }}
          - name: FLUENT_ELASTICSEARCH_USER
            value: {{ .user | quote }}
          - name: FLUENT_ELASTICSEARCH_PASSWORD
            value: {{ .password | quote }}
          - name: FLUENTD_SYSTEMD_CONF
            value: {{ $.Values.fluentd.containers.env.fluent.elastic.systemdConf | quote }}
        {{- end }}
        resources:
          {{- with .Values.fluentd.containers.env.fluent.resources }}
          limits:
            memory: {{ .limits.memory }}
          requests:
            cpu: {{ .requests.cpu }}
            memory: {{ .requests.memory }}
          {{- end }}
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: dockercontainerlogdirectory
          mountPath: /var/log/pods
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: {{ .Values.fluentd.containers.env.fluent.terminationGracePeriodSeconds }}
      volumes:
      - name: {{ .Values.fluentd.name }}
        configMap:
          name: {{ .Values.fluentd.name }}-config
      - name: varlog
        hostPath:
          path: /var/log
      - name: dockercontainerlogdirectory
        hostPath:
          path: /var/log/pods
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers