apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.fluentd.name }}
  namespace: {{ .Values.fluentd.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.fluentd.name }}-cr
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.fluentd.name }}-cr-binding
roleRef:
  kind: ClusterRole
  name: {{ .Values.fluentd.name }}-cr
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ .Values.fluentd.name }}
  namespace: {{ .Values.fluentd.namespace }}
---